# Generated by Django 3.2.13 on 2022-06-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=250)),
                ('about', models.TextField()),
            ],
        ),
    ]
