# Generated by Django 3.2.13 on 2022-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_team_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('image', models.ImageField(upload_to='pics3')),
            ],
        ),
    ]
